// ADD GENERAL DATA OF EACH SECTION (TOTALS, ACTIVE, ETC)
// DELETE THINGS LOGIC (USERS, CATEGORIES, TOOLS) ONLY STRONG DELETE FOR TESTING

// WORKERS
// REPET TOOL STRUCTURE AND OPTIONS

// MODEL ACTION MAINTENANCE NOTIFICATION RECORD

// PAGINATION IN ALL REGISTROLIST

// FILTERS IN PRINCIPAL REGISTROLIST

// EMI:
// SEGURIDAD SECTION
// ALERTAS DE VENCIMIENTOS
// DOC VIGENTE EN ART
// AGREGAR EN OBRA ESTADO DE SEGURIDAD
// HERRAMIENTAS - BUSCAR POR MENU DESPL (NORMALIZAR NOMBRES) AUTOCOMPLETAR
