// BREADCRUMB
// SMALL SIZE TABLE OPTIONS
// ADD GENERAL DATA OF EACH SECTION (TOTALS, ACTIVE, ETC)
// DELETE THINGS LOGIC (USERS, CATEGORIES, TOOLS) ONLY STRONG DELETE FOR TESTING

// TOOLS
// REMOVE QUICK UPDATE FROM TOOL CATEGORY IN TABLE
// REMOVE CUANTITY FROM TOOL MODEL AND ALL TOOL ITEMS

// PROJECTS
// REPET TOOL STRUCTURE AND OPTIONS

// WORKERS
// REPET TOOL STRUCTURE AND OPTIONS

